name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Scan for accessibility issues
      uses: microsoft/accessibility-insights-action@v3
      with:
          static-site-dir: ${{ github.workspace }}/site
          static-site-url-relative-path: /
    - name: Upload report artifact
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
          name: accessibility-reports
          path: ${{ github.workspace }}/_accessibility-reports
