name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Scan for accessibility issues
      uses: microsoft/accessibility-insights-action@v3
      with:
          static-site-dir: ${{ github.workspace }}/site
          scan-timeout: 6000000
          static-site-port: 12345
